### ISSUE TITLE
[Staging] On the /community/metrics page the text overlay the chart 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#270]
STR:

1. Go to https://support.allizom.org/en-US/community/metrics
2. Look at the first chart 

ER: The text doesn't overlay the chart.
AR: The text overlay the chart.
NOTE: Try to interact (hover over) with the other charts that are on the page, the behavior is different from the one that is on production https://support.mozilla.org/en-US/community/metrics

**Comment by madasan** [comment]
This page is not really used and probably will be replaced so it's not a priority atm.

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4312

I can't confirm whether the interactions are accurate on the other charts on the page, but it appears ok to me locally, and I fixed the text. 

<img width="1109" alt="Screen Shot 2020-04-15 at 1 48 41 PM" src="https://user-images.githubusercontent.com/202590/79369971-d9063d80-7f1f-11ea-9784-a6126b785bed.png">

**Comment by ovidiuboca1** [comment]
The issue is still reproducible on Mac OS X 10.14 with chrome browser. Print screen
<img width="1420" alt="Screenshot 2020-04-16 at 11 11 25" src="https://user-images.githubusercontent.com/54845678/79431740-82f2d200-7fd3-11ea-9cb6-7cb0ef7b19ff.png">


It is verified on Mac OS X 10.14 with FF, Windows 10 with FF and chrome and also mobile, and I can confirm the fix. 
CC @kkellydesign, @akatsoulas

**Comment by kkellydesign** [comment]
Can you try the staging server again with a hard refresh? that screenshot shows a grey box around the language select box above, which I also fixed, so that tells me Chrome is still pulling in the old CSS. I'm seeing the fix in Chrome here: 

https://support.allizom.org/en-US/community/metrics

<img width="1157" alt="Screen Shot 2020-04-16 at 11 14 44 AM" src="https://user-images.githubusercontent.com/202590/79473842-addd2600-7fd3-11ea-8202-fdf39a340c82.png">

**Comment by ovidiuboca1** [comment]
I just verify it and it works.
