### ISSUE TITLE
Forum search by selecting tags fix

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#344]
![Screen Shot 2020-04-14 at 4 36 26 PM](https://user-images.githubusercontent.com/54991698/79272081-e7e0e780-7e6e-11ea-86af-0dff5f1ecf2e.png)

When viewing a question page clicking from a forum .... on the side bar for logged in users and both logged out (we need to think through this, if we want to keep this function visible for both) --  you will see the tags listed --- when selecting a tag it then searches / filters the forum you just came from by that tag (creating the screenshot above).

This is both a UI fix and UX fix.
The UI looks broken and smashed together in this instance.
UX needs potentially some thinking... do we want to keep this feature or not? And who is this feature useful for?

**Comment by kkellydesign** [comment]
UI is fixed here: https://github.com/mozilla/kitsune/pull/4312
<img width="757" alt="Screen Shot 2020-04-15 at 1 09 23 PM" src="https://user-images.githubusercontent.com/202590/79366680-9ee66d00-7f1a-11ea-9e7a-7421fb5b4a1e.png">

Regarding the UX: my vote is to keep it as-is. There are multiple ways to get to this tag-filtered view of forum posts: 
* From the sidebar of a forum post, you can get to related posts
* From the forum list view, each question displays the tags at the top. (See Firefox, bookmarks etc in your screenshot above.) You can also get to this view from those links. 

IMO, if you're removing the ability to click on the tags and using them to filter your list or find similar questions, then there's no reason to display tags at all. I think it's equally useful for logged in and logged-out users.

**Comment by ovidiuboca1** [comment]
2 Issues:

1. On Mac OS X 10.14 with chrome, the issue is still there.
2. I f I select "Firefox" tag nothing happens, I used this link - https://support.allizom.org/en-US/questions/firefox?tagged=desktop

On Windows 10 with FF and chrome, the issue is fixed, also on Mac OS with FF  and mobile the issue is fixed. 
@kkellydesign @akatsoulas

**Comment by kkellydesign** [comment]
That seems to be the intended behavior. The slug for the "firefox" tag is "desktop", so the "desktop" and "firefox" tags are functionally equivalent.
