### ISSUE TITLE
[AAQ] Email notifications are not received

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#433]
**Affected platforms:**
MacOS X 14.0
Windows 10 64-bit
Android and iOS 

**Browsers**
Firefox 76.0 
Firefox 68.8.0
Chrome 81
Safari

**Environments**
Dev : https://support-dev.allizom.org/en-US/
Stage: https://support.allizom.org/en-US

**Precondition:** 
Create account A and Account B on either Dev or Stage. 
Sign in using account A go through the AAQ flow :  Get Help> Ask the Community> Select product > Select "Ask Now" 

**Steps to reproduce:**

1.Reach in AAQ form. 
2. Fill in the required from and verify that "Email me when someone answers the thread". 
3. Post the question. 
4. On a second browser sign in on the same environment with account B. 
5. Post a reply on account's A question. 
6. Check Account A's email inbox. 

**Expected results:**
An email notification should be received. 

**Actual Results:**
No notification is received in either dev or stage environment. 

NOTES: 
1. This also applies for the other Email notification avenues: 
- selecting Question Tools> Get email updates
- selecting 'I have this problem too' > Send Updates. 
- adding a reply > select "Needs information"

2.It was confirmed through slack  that only stage is supposed to receive email notifications https://mozilla.slack.com/archives/G4VFFUYE4/p1589195670081300

![image](https://user-images.githubusercontent.com/53306802/81691623-ca02a480-9465-11ea-9be8-a3a85e9526a5.png)

![image](https://user-images.githubusercontent.com/53306802/81691535-a5a6c800-9465-11ea-892b-15088e386a97.png)

**Comment by LeoMcA** [comment]
This should be fixed on dev, we had a massive backlog of jobs which caused the emails to not be sent in a timely manner. They should be doing so now.

**Comment by mirunacurtean** [comment]
@LeoMcA Re-tested this in dev on https://support-dev.allizom.org/en-US/questions/1250997 and I still receive any email notifications on mcurtean4@mailinator.com's inbox for either of the posted replies. 
Waited for about 10 minutes in case there was some delay but still no results.

**Comment by akatsoulas** [comment]
This is related to dev. Prod is working as it should. @mirunacurtean shall we close this?

**Comment by mirunacurtean** [comment]
@akatsoulas 
yes. tested in production and it works as expected. I receive notifications as both question owner and 'get email' subscriber. 
![image](https://user-images.githubusercontent.com/53306802/82240375-fecd9a80-9942-11ea-9a6a-4ff09b613499.png)
