### ISSUE TITLE
Move Solved the Problem button to the answer-tools section

### ISSUE THREAD

**Issue by jscher2000** [mozilla/sumo-project#95]
The aim is to improve use of the Solved the Problem button. We would like solved threads to be marked as such.

Some users do not see the solution button on the right side of an answer and only click helpful => Yes below it. There is also some confusion about how to "unsolve" a thread when a link in an email notification was selected inadvertently. Contributors generally agree that helpful => No does not provide useful information. See: https://support.mozilla.org/forums/contributors/713316

**Current appearance**

![Fx68-answer-current](https://user-images.githubusercontent.com/8264646/61189975-ce91dd00-a649-11e9-9d34-5cb952b8c836.png)

**Proposed Change**

Move the solution button to the answer-tools section below the reply, and remove the No button. This primarily involves moving a form up a few lines in the code, and removing tags that would give it an inconsistent style.

![Fx68-answer-revised](https://user-images.githubusercontent.com/8264646/61189981-dd788f80-a649-11e9-816b-3c718dec3bc7.png)

**Attached files**

(1) Proposed revised code for https://github.com/mozilla/kitsune/blob/master/kitsune/questions/jinja2/questions/includes/answer.html

[answer_html_revised.txt](https://github.com/mozilla/kitsune/files/3390473/answer_html_revised.txt)

(2) Code diff for reference (generated on a randomly selected website)

[answer_html_diff.pdf](https://github.com/mozilla/kitsune/files/3390474/answer_html_diff.pdf)

**Comment by wsmwk** [comment]
see also #400

**Comment by denyshon** [comment]
@jscher2000 @AliceWyman can we consider this resolved now?

**Comment by AliceWyman** [comment]
It looks like the original issue, _Move the solution button to the answer-tools section below the reply_, has been resolved but the secondary issue, _remove the No button_ is not resolved since the Yes and No buttons have been replaced with "Thumbs up" and "Thumbs down" buttons, as shown in the related [bug 1566350](https://bugzilla.mozilla.org/show_bug.cgi?id=1566350) attachment, [2020-04-14 17:26 EDT](https://bugzilla.mozilla.org/show_bug.cgi?id=1566350#c20).  Note [comment 41](https://bugzilla.mozilla.org/show_bug.cgi?id=1566350#c41) which added a link to this issue and mentions https://github.com/mozilla/sumo/issues/400 _that got closed as "stale"_.   [Bug 1566350](https://bugzilla.mozilla.org/show_bug.cgi?id=1566350) is currently unresolved. It was updated by Emil Ghitta, QA [:emilghitta] in Jan 2025 as Type: task → enhancement.

**Comment by jscher2000** [comment]
Looks good, hard to miss if people read the whole reply.

<img width="864" height="279" alt="Image" src="https://github.com/user-attachments/assets/5189b7e5-fae7-4842-8754-ad52d6633eaa" />

**Comment by denyshon** [comment]
@jscher2000 if so, I would suggest closing this issue and opening another one for removing the dislike button. The latter is not visible at all here, and since the button has been preserved on redesign, it's probably not even considered. A new discussion will be more useful in my opinion

**Comment by emilghittasv** [comment]
I agree. Let's close this particular issue as fixed and open a new discussion regarding the "Thumbs up/down" button.
